package main

import (
	"math/rand"
	"time"
)

var domain = func() func() string {

	var seed = rand.NewSource(time.Now().Unix())
	var random = rand.New(seed)

	// Popular domains. Thanks to:
	// https://github.com/mailcheck/mailcheck/wiki/List-of-Popular-Domains
	var domains = []string{
		"alice.it",
		"aol.com",
		"aol.it",
		"arnet.com.ar",
		"att.net",
		"bellsouth.net",
		"blueyonder.co.uk",
		"bol.com.br",
		"bt.com",
		"btinternet.com",
		"charter.net",
		"comcast.net",
		"cox.net",
		"daum.net",
		"earthlink.net",
		"email.com",
		"email.it",
		"facebook.com",
		"fastmail.fm",
		"fibertel.com.ar",
		"free.fr",
		"freeserve.co.uk",
		"games.com",
		"globo.com",
		"globomail.com",
		"gmail.com",
		"gmx.com",
		"gmx.de",
		"gmx.fr",
		"gmx.net",
		"google.com",
		"googlemail.com",
		"hanmail.net",
		"hotmail.be",
		"hotmail.co.uk",
		"hotmail.com",
		"hotmail.com.ar",
		"hotmail.com.br",
		"hotmail.com.mx",
		"hotmail.de",
		"hotmail.es",
		"hotmail.fr",
		"hotmail.it",
		"hush.com",
		"hushmail.com",
		"icloud.com",
		"ig.com.br",
		"iname.com",
		"inbox.com",
		"itelefonica.com.br",
		"juno.com",
		"laposte.net",
		"lavabit.com",
		"libero.it",
		"list.ru",
		"live.be",
		"live.co.uk",
		"live.com",
		"live.com.ar",
		"live.com.mx",
		"live.de",
		"live.fr",
		"live.it",
		"love.com",
		"mac.com",
		"mail.com",
		"mail.ru",
		"me.com",
		"msn.com",
		"nate.com",
		"naver.com",
		"neuf.fr",
		"ntlworld.com",
		"o2.co.uk",
		"oi.com.br",
		"online.de",
		"orange.fr",
		"orange.net",
		"outlook.com",
		"outlook.com.br",
		"pobox.com",
		"poste.it",
		"prodigy.net.mx",
		"protonmail.com",
		"qq.com",
		"r7.com",
		"rambler.ru",
		"rocketmail.com",
		"safe-mail.net",
		"sbcglobal.net",
		"sfr.fr",
		"sina.com",
		"sky.com",
		"skynet.be",
		"speedy.com.ar",
		"t-online.de",
		"talktalk.co.uk",
		"telenet.be",
		"teletu.it",
		"terra.com.br",
		"tin.it",
		"tiscali.co.uk",
		"tiscali.it",
		"tvcablenet.be",
		"uol.com.br",
		"verizon.net",
		"virgilio.it",
		"virgin.net",
		"virginmedia.com",
		"voo.be",
		"wanadoo.co.uk",
		"wanadoo.fr",
		"web.de",
		"wow.com",
		"ya.ru",
		"yahoo.co.id",
		"yahoo.co.in",
		"yahoo.co.jp",
		"yahoo.co.kr",
		"yahoo.co.uk",
		"yahoo.com",
		"yahoo.com.ar",
		"yahoo.com.br",
		"yahoo.com.mx",
		"yahoo.com.ph",
		"yahoo.com.sg",
		"yahoo.de",
		"yahoo.fr",
		"yahoo.it",
		"yandex.com",
		"yandex.ru",
		"ygm.com",
		"ymail.com",
		"zipmail.com.br",
		"zoho.com",
	}

	return func() string {
		return domains[random.Intn(len(domains))]
	}
}()
